services:
  database:
    image: mariadb:10.11
    container_name: mariadb_hogwarts
    restart: always
    env_file:
      - .env
    environment:
      # Las variables se leen del archivo .env
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: hogwarts_${EXAMEN_SUFFIX}
      MYSQL_USER: examen_${EXAMEN_SUFFIX}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/imoya-21/aaee_mapamundi_sb:latest
    container_name: aaee_mapamundi_app_imy
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - database
    environment:
      # Configuración de conexión para Spring Boot
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/hogwarts_${EXAMEN_SUFFIX}
      SPRING_DATASOURCE_USERNAME: examen_${EXAMEN_SUFFIX}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
