services:
  # Servicio de Base de Datos
  database:
    image: mariadb:10.11 # O la versión que prefieras
    container_name: mariadb_hogwarts
    restart: always
    environment:
      # Estos nombres deben coincidir con lo que pide el examen
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Se define en los secretos/variables
      MYSQL_DATABASE: hogwarts_ejm           # <--- Cambia xxx por tu identificador
      MYSQL_USER: examen_ejm                 # <--- Cambia xxx por tu identificador
      MYSQL_PASSWORD: ${DB_PASSWORD}         # Se define en los secretos/variables
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Servicio de la Aplicación Java
  app:
    # IMPORTANTE: Esta es la imagen que genera tu GitHub Actions
    image: ghcr.io/imoya-21/examen_aaee_eval3:latest
    container_name: app_mapamundi
    depends_on:
      - database
    restart: always
    environment:
      # Configuración para que Spring Boot encuentre la base de datos
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/hogwarts_xxx
      SPRING_DATASOURCE_USERNAME: examen_xxx
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Si tu aplicación usa Hibernate para crear las tablas automáticamente:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  db_data:
