name: Primer flujo de trabajo CI/CD (Build, Test and Push Docker Image)

on:
  push:
    branches:
      - '**' # Esto ejecutará el pipeline en cualquier rama

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Configuración Java para TEST y Build
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Cambia a 23 si es estrictamente necesario
          cache: 'maven' # Añadir caché acelera mucho los builds posteriores

      - name: Construir proyecto con Maven (Genera el .jar)
        run: mvn clean package -DskipTests # -DskipTests opcional si quieres ir más rápido

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Usamos la variable del repositorio para que coincida exactamente con el examen
          tags: ghcr.io/${{ github.repository }}:latest
